language: java
jdk:
- oraclejdk8
addons:
  firefox: "39.0"
#Utilización de los tests de Selenium
beforescript:

- "export DISPLAY=:99.0"
- sh -e /etc/init.d/xvfb start
- sleep 5
after_success:
  - bash <(curl -s https://codecov.io/bash)
